services:
  mongodbi_db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_URL=${MONGO_URL}
    volumes:
      - mongodb-data:/data/db
  custom_app:
    build: ./
    ports:
      - "8080:8080"

volumes:
  mongodb-data:
